### ISSUE TITLE
No durability

### ISSUE THREAD

**Issue by mhsjlw** [GlowstoneMC/GlowstonePlusPlus#157]
**Java version**: `build 1.8.0_66-b17`
**OS**: `Mac OSX El Capitan (10.11)`
**Glowstone ver.**: `newest (40df0c7)`

**What I did**:
I made a shovel in a crafting table then started digging up sand blocks. The durability showed up on the tool but after I picked up the blocks that it dug the durability disappeared on the shovel.

**Comment by mastercoms** [comment]
Durability isn't implemented at all. The change in durability you're seeing is the client thinking the durability is decreasing, and then the server updates the inventory when the block is picked up, so the client is told that the durability did not decrease in the first place.

**Comment by mhsjlw** [comment]
Alright, sorry. I was unaware that items don't have a durability yet. Is there a file I can view that has all of the features that are currently implemented and ones that need to be?

**Comment by twizmwazin** [comment]
There isn't a list of implemented features that I'm aware of. There will probably always be more to implement though, if you are looking for something to implement. If you are looking to use glowstone++ for production, it can handle being a creative server, but survival is not there yet.

**Comment by mastercoms** [comment]
survival is pretty close, though.

**Comment by mhsjlw** [comment]
I'm working on making it perfect :)

**Comment by CrabeMan** [comment]
I can pull request from GlowstoneMC/Glowstone#627
Or you can copy the code.

**Comment by mastercoms** [comment]
We already have a PR: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/185

**Comment by mastercoms** [comment]
And here is an incomplete list of features: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/wiki/Current-Features

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/1c6f71f1cc138ee379302a7d41f4f6b37aa83e7b
